<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \App\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'NombreUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'CorreoUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'Username', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'Password', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'Apellidos', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'cvUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'solicitas', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'participas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'NombreUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'CorreoUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'Username', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'Password', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'Apellidos', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'cvUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'solicitas', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'participas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreUsuario(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreUsuario', []);

        return parent::getNombreUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreUsuario(string $NombreUsuario): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreUsuario', [$NombreUsuario]);

        return parent::setNombreUsuario($NombreUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoUsuario(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoUsuario', []);

        return parent::getCorreoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoUsuario(string $CorreoUsuario): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoUsuario', [$CorreoUsuario]);

        return parent::setCorreoUsuario($CorreoUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $Username): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$Username]);

        return parent::setUsername($Username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $Password): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$Password]);

        return parent::setPassword($Password);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos(?string $Apellidos): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$Apellidos]);

        return parent::setApellidos($Apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvUsuario(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvUsuario', []);

        return parent::getCvUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvUsuario(?string $cvUsuario): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvUsuario', [$cvUsuario]);

        return parent::setCvUsuario($cvUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitas', []);

        return parent::getSolicitas();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicita(\App\Entity\Solicita $solicita): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicita', [$solicita]);

        return parent::addSolicita($solicita);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicita(\App\Entity\Solicita $solicita): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicita', [$solicita]);

        return parent::removeSolicita($solicita);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipas', []);

        return parent::getParticipas();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipa(\App\Entity\Participa $participa): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipa', [$participa]);

        return parent::addParticipa($participa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipa(\App\Entity\Participa $participa): \App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipa', [$participa]);

        return parent::removeParticipa($participa);
    }

}
