<?php

namespace ContainerBnAotPw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CrhbEmPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.crhbEmP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.crhbEmP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContenidoController::delete' => ['privates', '.service_locator.vmqz2t3', 'get_ServiceLocator_Vmqz2t3Service', true],
            'App\\Controller\\ContenidoController::edit' => ['privates', '.service_locator.q9WzDsK', 'get_ServiceLocator_Q9WzDsKService', true],
            'App\\Controller\\ContenidoController::index' => ['privates', '.service_locator.R3wYcPt', 'get_ServiceLocator_R3wYcPtService', true],
            'App\\Controller\\ContenidoController::new' => ['privates', '.service_locator.SRtF.2R', 'get_ServiceLocator_SRtF_2RService', true],
            'App\\Controller\\ContenidoController::show' => ['privates', '.service_locator..57cKV7', 'get_ServiceLocator__57cKV7Service', true],
            'App\\Controller\\EmpleoController::delete' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController::edit' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController::index' => ['privates', '.service_locator.MAoJ4pW', 'get_ServiceLocator_MAoJ4pWService', true],
            'App\\Controller\\EmpleoController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EmpleoController::show' => ['privates', '.service_locator.qn8H32k', 'get_ServiceLocator_Qn8H32kService', true],
            'App\\Controller\\EventoController::delete' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController::edit' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController::index' => ['privates', '.service_locator.iqTlsWm', 'get_ServiceLocator_IqTlsWmService', true],
            'App\\Controller\\EventoController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EventoController::show' => ['privates', '.service_locator.Y18PFmu', 'get_ServiceLocator_Y18PFmuService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ContenidoController:delete' => ['privates', '.service_locator.vmqz2t3', 'get_ServiceLocator_Vmqz2t3Service', true],
            'App\\Controller\\ContenidoController:edit' => ['privates', '.service_locator.q9WzDsK', 'get_ServiceLocator_Q9WzDsKService', true],
            'App\\Controller\\ContenidoController:index' => ['privates', '.service_locator.R3wYcPt', 'get_ServiceLocator_R3wYcPtService', true],
            'App\\Controller\\ContenidoController:new' => ['privates', '.service_locator.SRtF.2R', 'get_ServiceLocator_SRtF_2RService', true],
            'App\\Controller\\ContenidoController:show' => ['privates', '.service_locator..57cKV7', 'get_ServiceLocator__57cKV7Service', true],
            'App\\Controller\\EmpleoController:delete' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController:edit' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController:index' => ['privates', '.service_locator.MAoJ4pW', 'get_ServiceLocator_MAoJ4pWService', true],
            'App\\Controller\\EmpleoController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EmpleoController:show' => ['privates', '.service_locator.qn8H32k', 'get_ServiceLocator_Qn8H32kService', true],
            'App\\Controller\\EventoController:delete' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController:edit' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController:index' => ['privates', '.service_locator.iqTlsWm', 'get_ServiceLocator_IqTlsWmService', true],
            'App\\Controller\\EventoController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EventoController:show' => ['privates', '.service_locator.Y18PFmu', 'get_ServiceLocator_Y18PFmuService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ContenidoController::delete' => '?',
            'App\\Controller\\ContenidoController::edit' => '?',
            'App\\Controller\\ContenidoController::index' => '?',
            'App\\Controller\\ContenidoController::new' => '?',
            'App\\Controller\\ContenidoController::show' => '?',
            'App\\Controller\\EmpleoController::delete' => '?',
            'App\\Controller\\EmpleoController::edit' => '?',
            'App\\Controller\\EmpleoController::index' => '?',
            'App\\Controller\\EmpleoController::new' => '?',
            'App\\Controller\\EmpleoController::show' => '?',
            'App\\Controller\\EventoController::delete' => '?',
            'App\\Controller\\EventoController::edit' => '?',
            'App\\Controller\\EventoController::index' => '?',
            'App\\Controller\\EventoController::new' => '?',
            'App\\Controller\\EventoController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ContenidoController:delete' => '?',
            'App\\Controller\\ContenidoController:edit' => '?',
            'App\\Controller\\ContenidoController:index' => '?',
            'App\\Controller\\ContenidoController:new' => '?',
            'App\\Controller\\ContenidoController:show' => '?',
            'App\\Controller\\EmpleoController:delete' => '?',
            'App\\Controller\\EmpleoController:edit' => '?',
            'App\\Controller\\EmpleoController:index' => '?',
            'App\\Controller\\EmpleoController:new' => '?',
            'App\\Controller\\EmpleoController:show' => '?',
            'App\\Controller\\EventoController:delete' => '?',
            'App\\Controller\\EventoController:edit' => '?',
            'App\\Controller\\EventoController:index' => '?',
            'App\\Controller\\EventoController:new' => '?',
            'App\\Controller\\EventoController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
