<?php

namespace Container8oDE62S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiContenidoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiContenidoController' shared autowired service.
     *
     * @return \App\Controller\ApiContenidoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiContenidoController.php';

        $container->services['App\\Controller\\ApiContenidoController'] = $instance = new \App\Controller\ApiContenidoController(($container->privates['App\\Repository\\ContenidoRepository'] ?? $container->load('getContenidoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\ApiContenidoController', $container));

        return $instance;
    }
}
