<?php

namespace Container1VyNrWM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IqTlsWmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iqTlsWm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iqTlsWm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contenidoRepository' => ['privates', 'App\\Repository\\ContenidoRepository', 'getContenidoRepositoryService', true],
            'empleoRepository' => ['privates', 'App\\Repository\\EmpleoRepository', 'getEmpleoRepositoryService', true],
            'eventoRepository' => ['privates', 'App\\Repository\\EventoRepository', 'getEventoRepositoryService', true],
        ], [
            'contenidoRepository' => 'App\\Repository\\ContenidoRepository',
            'empleoRepository' => 'App\\Repository\\EmpleoRepository',
            'eventoRepository' => 'App\\Repository\\EventoRepository',
        ]);
    }
}
