<?php

<<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container1VyNrWM/getEvento2Service.php
namespace Container1VyNrWM;
========
namespace ContainerRPzqUxu;

>>>>>>>> main:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/getEvento2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvento2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tkLVMLM.App\Entity\Evento' shared service.
     *
     * @return \App\Entity\Evento
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tkLVMLM": it references class "App\\Entity\\Evento" but no such service exists.');
    }
}
