<?php

namespace ContainerVNeTNLV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__57cKV7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..57cKV7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..57cKV7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contenido' => ['privates', '.errored..service_locator..57cKV7.App\\Entity\\Contenido', NULL, 'Cannot autowire service ".service_locator..57cKV7": it references class "App\\Entity\\Contenido" but no such service exists.'],
        ], [
            'contenido' => 'App\\Entity\\Contenido',
        ]);
    }
}
