<?php

namespace ContainerAUEwEoj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P84xtg9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p84xtg9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p84xtg9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contenidoRepository' => ['privates', 'App\\Repository\\ContenidoRepository', 'getContenidoRepositoryService', true],
        ], [
            'contenidoRepository' => 'App\\Repository\\ContenidoRepository',
        ]);
    }
}
