<?php

namespace ContainerAUEwEoj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SOWg_70.App\Entity\Evento' shared service.
     *
     * @return \App\Entity\Evento
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SOWg_70": it references class "App\\Entity\\Evento" but no such service exists.');
    }
}
