<?php

namespace ContainerRPzqUxu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TkLVMLMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tkLVMLM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tkLVMLM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evento' => ['privates', '.errored..service_locator.tkLVMLM.App\\Entity\\Evento', NULL, 'Cannot autowire service ".service_locator.tkLVMLM": it references class "App\\Entity\\Evento" but no such service exists.'],
        ], [
            'evento' => 'App\\Entity\\Evento',
        ]);
    }
}
