<?php

<<<<<<< HEAD
<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container2x9EUrJ/get_ServiceLocator_TkLVMLMService.php
namespace Container2x9EUrJ;
=======
=======
<<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container1VyNrWM/get_ServiceLocator_Y18PFmuService.php
namespace Container1VyNrWM;
========
>>>>>>> cebea07cd9427ec42e23db05512f7a6a976d3b7f
namespace ContainerRPzqUxu;
>>>>>>> c3c3798b07e811dc68b12039783577c1443ac405:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_TkLVMLMService.php

>>>>>>>> main:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_TkLVMLMService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TkLVMLMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tkLVMLM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tkLVMLM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evento' => ['privates', '.errored..service_locator.tkLVMLM.App\\Entity\\Evento', NULL, 'Cannot autowire service ".service_locator.tkLVMLM": it references class "App\\Entity\\Evento" but no such service exists.'],
        ], [
            'evento' => 'App\\Entity\\Evento',
        ]);
    }
}
