<?php

<<<<<<< HEAD
<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container24eWKRp/get_ServiceLocator_Jjfoa6Service.php
namespace Container24eWKRp;
=======
=======
<<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container1VyNrWM/get_ServiceLocator_Jjfoa6Service.php
namespace Container1VyNrWM;
========
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
namespace ContainerRPzqUxu;
>>>>>>> c3c3798b07e811dc68b12039783577c1443ac405:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_UupoQDHService.php

>>>>>>>> main:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_UupoQDHService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<< HEAD
<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container24eWKRp/get_ServiceLocator_Jjfoa6Service.php
=======
<<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container1VyNrWM/get_ServiceLocator_Jjfoa6Service.php
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
class get_ServiceLocator_Jjfoa6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jjfoa6_' shared service.
<<<<<<< HEAD
=======
=======
========
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
class get_ServiceLocator_UupoQDHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UupoQDH' shared service.
<<<<<<< HEAD
>>>>>>> c3c3798b07e811dc68b12039783577c1443ac405:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_UupoQDHService.php
=======
>>>>>>>> main:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_UupoQDHService.php
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<< HEAD
<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container24eWKRp/get_ServiceLocator_Jjfoa6Service.php
=======
<<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container1VyNrWM/get_ServiceLocator_Jjfoa6Service.php
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
        return $container->privates['.service_locator.jjfoa6_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContenidoController::delete' => ['privates', '.service_locator.vmqz2t3', 'get_ServiceLocator_Vmqz2t3Service', true],
            'App\\Controller\\ContenidoController::edit' => ['privates', '.service_locator.q9WzDsK', 'get_ServiceLocator_Q9WzDsKService', true],
            'App\\Controller\\ContenidoController::index' => ['privates', '.service_locator.R3wYcPt', 'get_ServiceLocator_R3wYcPtService', true],
            'App\\Controller\\ContenidoController::new' => ['privates', '.service_locator.SRtF.2R', 'get_ServiceLocator_SRtF_2RService', true],
            'App\\Controller\\ContenidoController::show' => ['privates', '.service_locator..57cKV7', 'get_ServiceLocator__57cKV7Service', true],
            'App\\Controller\\EmpleoController::delete' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController::edit' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController::index' => ['privates', '.service_locator.MAoJ4pW', 'get_ServiceLocator_MAoJ4pWService', true],
            'App\\Controller\\EmpleoController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EmpleoController::show' => ['privates', '.service_locator.qn8H32k', 'get_ServiceLocator_Qn8H32kService', true],
            'App\\Controller\\EventoController::delete' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController::edit' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController::index' => ['privates', '.service_locator.iqTlsWm', 'get_ServiceLocator_IqTlsWmService', true],
            'App\\Controller\\EventoController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EventoController::show' => ['privates', '.service_locator.Y18PFmu', 'get_ServiceLocator_Y18PFmuService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.HIXq1dW', 'get_ServiceLocator_HIXq1dWService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ContenidoController:delete' => ['privates', '.service_locator.vmqz2t3', 'get_ServiceLocator_Vmqz2t3Service', true],
            'App\\Controller\\ContenidoController:edit' => ['privates', '.service_locator.q9WzDsK', 'get_ServiceLocator_Q9WzDsKService', true],
            'App\\Controller\\ContenidoController:index' => ['privates', '.service_locator.R3wYcPt', 'get_ServiceLocator_R3wYcPtService', true],
            'App\\Controller\\ContenidoController:new' => ['privates', '.service_locator.SRtF.2R', 'get_ServiceLocator_SRtF_2RService', true],
            'App\\Controller\\ContenidoController:show' => ['privates', '.service_locator..57cKV7', 'get_ServiceLocator__57cKV7Service', true],
            'App\\Controller\\EmpleoController:delete' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController:edit' => ['privates', '.service_locator.MNG5ObC', 'get_ServiceLocator_MNG5ObCService', true],
            'App\\Controller\\EmpleoController:index' => ['privates', '.service_locator.MAoJ4pW', 'get_ServiceLocator_MAoJ4pWService', true],
            'App\\Controller\\EmpleoController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EmpleoController:show' => ['privates', '.service_locator.qn8H32k', 'get_ServiceLocator_Qn8H32kService', true],
            'App\\Controller\\EventoController:delete' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController:edit' => ['privates', '.service_locator.FudmbnZ', 'get_ServiceLocator_FudmbnZService', true],
            'App\\Controller\\EventoController:index' => ['privates', '.service_locator.iqTlsWm', 'get_ServiceLocator_IqTlsWmService', true],
            'App\\Controller\\EventoController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\EventoController:show' => ['privates', '.service_locator.Y18PFmu', 'get_ServiceLocator_Y18PFmuService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.HIXq1dW', 'get_ServiceLocator_HIXq1dWService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
<<<<<<< HEAD
=======
=======
========
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
        return $container->privates['.service_locator.UupoQDH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContenidoController::delete' => ['privates', '.service_locator.BFO3KOY', 'get_ServiceLocator_BFO3KOYService', true],
            'App\\Controller\\ContenidoController::edit' => ['privates', '.service_locator.DQnconH', 'get_ServiceLocator_DQnconHService', true],
            'App\\Controller\\ContenidoController::index' => ['privates', '.service_locator.p84xtg9', 'get_ServiceLocator_P84xtg9Service', true],
            'App\\Controller\\ContenidoController::new' => ['privates', '.service_locator.Hjz3HR0', 'get_ServiceLocator_Hjz3HR0Service', true],
            'App\\Controller\\ContenidoController::show' => ['privates', '.service_locator.OlaUaSd', 'get_ServiceLocator_OlaUaSdService', true],
            'App\\Controller\\EmpleoController::delete' => ['privates', '.service_locator.J0i9nl8', 'get_ServiceLocator_J0i9nl8Service', true],
            'App\\Controller\\EmpleoController::edit' => ['privates', '.service_locator.J0i9nl8', 'get_ServiceLocator_J0i9nl8Service', true],
            'App\\Controller\\EmpleoController::index' => ['privates', '.service_locator.I.Fg2WZ', 'get_ServiceLocator_I_Fg2WZService', true],
            'App\\Controller\\EmpleoController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EmpleoController::show' => ['privates', '.service_locator.2VPHbV7', 'get_ServiceLocator_2VPHbV7Service', true],
            'App\\Controller\\EventoController::delete' => ['privates', '.service_locator.SOWg_70', 'get_ServiceLocator_SOWg70Service', true],
            'App\\Controller\\EventoController::edit' => ['privates', '.service_locator.SOWg_70', 'get_ServiceLocator_SOWg70Service', true],
            'App\\Controller\\EventoController::index' => ['privates', '.service_locator.keEqB9B', 'get_ServiceLocator_KeEqB9BService', true],
            'App\\Controller\\EventoController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EventoController::show' => ['privates', '.service_locator.tkLVMLM', 'get_ServiceLocator_TkLVMLMService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3OYTKdS', 'get_ServiceLocator_3OYTKdSService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ContenidoController:delete' => ['privates', '.service_locator.BFO3KOY', 'get_ServiceLocator_BFO3KOYService', true],
            'App\\Controller\\ContenidoController:edit' => ['privates', '.service_locator.DQnconH', 'get_ServiceLocator_DQnconHService', true],
            'App\\Controller\\ContenidoController:index' => ['privates', '.service_locator.p84xtg9', 'get_ServiceLocator_P84xtg9Service', true],
            'App\\Controller\\ContenidoController:new' => ['privates', '.service_locator.Hjz3HR0', 'get_ServiceLocator_Hjz3HR0Service', true],
            'App\\Controller\\ContenidoController:show' => ['privates', '.service_locator.OlaUaSd', 'get_ServiceLocator_OlaUaSdService', true],
            'App\\Controller\\EmpleoController:delete' => ['privates', '.service_locator.J0i9nl8', 'get_ServiceLocator_J0i9nl8Service', true],
            'App\\Controller\\EmpleoController:edit' => ['privates', '.service_locator.J0i9nl8', 'get_ServiceLocator_J0i9nl8Service', true],
            'App\\Controller\\EmpleoController:index' => ['privates', '.service_locator.I.Fg2WZ', 'get_ServiceLocator_I_Fg2WZService', true],
            'App\\Controller\\EmpleoController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EmpleoController:show' => ['privates', '.service_locator.2VPHbV7', 'get_ServiceLocator_2VPHbV7Service', true],
            'App\\Controller\\EventoController:delete' => ['privates', '.service_locator.SOWg_70', 'get_ServiceLocator_SOWg70Service', true],
            'App\\Controller\\EventoController:edit' => ['privates', '.service_locator.SOWg_70', 'get_ServiceLocator_SOWg70Service', true],
            'App\\Controller\\EventoController:index' => ['privates', '.service_locator.keEqB9B', 'get_ServiceLocator_KeEqB9BService', true],
            'App\\Controller\\EventoController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EventoController:show' => ['privates', '.service_locator.tkLVMLM', 'get_ServiceLocator_TkLVMLMService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3OYTKdS', 'get_ServiceLocator_3OYTKdSService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
<<<<<<< HEAD
>>>>>>> c3c3798b07e811dc68b12039783577c1443ac405:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_UupoQDHService.php
=======
>>>>>>>> main:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_UupoQDHService.php
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
        ], [
            'App\\Controller\\ContenidoController::delete' => '?',
            'App\\Controller\\ContenidoController::edit' => '?',
            'App\\Controller\\ContenidoController::index' => '?',
            'App\\Controller\\ContenidoController::new' => '?',
            'App\\Controller\\ContenidoController::show' => '?',
            'App\\Controller\\EmpleoController::delete' => '?',
            'App\\Controller\\EmpleoController::edit' => '?',
            'App\\Controller\\EmpleoController::index' => '?',
            'App\\Controller\\EmpleoController::new' => '?',
            'App\\Controller\\EmpleoController::show' => '?',
            'App\\Controller\\EventoController::delete' => '?',
            'App\\Controller\\EventoController::edit' => '?',
            'App\\Controller\\EventoController::index' => '?',
            'App\\Controller\\EventoController::new' => '?',
            'App\\Controller\\EventoController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ContenidoController:delete' => '?',
            'App\\Controller\\ContenidoController:edit' => '?',
            'App\\Controller\\ContenidoController:index' => '?',
            'App\\Controller\\ContenidoController:new' => '?',
            'App\\Controller\\ContenidoController:show' => '?',
            'App\\Controller\\EmpleoController:delete' => '?',
            'App\\Controller\\EmpleoController:edit' => '?',
            'App\\Controller\\EmpleoController:index' => '?',
            'App\\Controller\\EmpleoController:new' => '?',
            'App\\Controller\\EmpleoController:show' => '?',
            'App\\Controller\\EventoController:delete' => '?',
            'App\\Controller\\EventoController:edit' => '?',
            'App\\Controller\\EventoController:index' => '?',
            'App\\Controller\\EventoController:new' => '?',
            'App\\Controller\\EventoController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
