<?php

<<<<<<< HEAD
<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container24eWKRp/get_ServiceLocator_Qn8H32kService.php
namespace Container24eWKRp;
=======
=======
<<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container1VyNrWM/get_ServiceLocator_Qn8H32kService.php
namespace Container1VyNrWM;
========
>>>>>>> 477da2d03e5a4f1bb6508b77c2aa473ff27ca652
namespace ContainerRPzqUxu;
>>>>>>> c3c3798b07e811dc68b12039783577c1443ac405:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_2VPHbV7Service.php

>>>>>>>> main:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/get_ServiceLocator_2VPHbV7Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2VPHbV7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2VPHbV7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2VPHbV7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empleo' => ['privates', '.errored..service_locator.2VPHbV7.App\\Entity\\Empleo', NULL, 'Cannot autowire service ".service_locator.2VPHbV7": it references class "App\\Entity\\Empleo" but no such service exists.'],
        ], [
            'empleo' => 'App\\Entity\\Empleo',
        ]);
    }
}
