<?php

namespace ContainerRPzqUxu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OlaUaSdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OlaUaSd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OlaUaSd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contenido' => ['privates', '.errored..service_locator.OlaUaSd.App\\Entity\\Contenido', NULL, 'Cannot autowire service ".service_locator.OlaUaSd": it references class "App\\Entity\\Contenido" but no such service exists.'],
        ], [
            'contenido' => 'App\\Entity\\Contenido',
        ]);
    }
}
