<?php

<<<<<<< HEAD:Aplicación/APP-ADMIN/var/cache/dev/Container24eWKRp/getEmpleo2Service.php
namespace Container24eWKRp;
=======
namespace ContainerRPzqUxu;
>>>>>>> c3c3798b07e811dc68b12039783577c1443ac405:Aplicación/APP-ADMIN/var/cache/dev/ContainerRPzqUxu/getEmpleo2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpleo2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J0i9nl8.App\Entity\Empleo' shared service.
     *
     * @return \App\Entity\Empleo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.J0i9nl8": it references class "App\\Entity\\Empleo" but no such service exists.');
    }
}
