<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container24eWKRp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container24eWKRp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container24eWKRp.legacy');
=======
if (\class_exists(\Container2x9EUrJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2x9EUrJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2x9EUrJ.legacy');
>>>>>>> 35d8e8d6c43cb91c2da1943efcc35b099aaf3e45

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container24eWKRp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container24eWKRp\App_KernelDevDebugContainer([
    'container.build_hash' => '24eWKRp',
    'container.build_id' => '34121e70',
    'container.build_time' => 1645186747,
], __DIR__.\DIRECTORY_SEPARATOR.'Container24eWKRp');
=======
    \class_alias(\Container2x9EUrJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2x9EUrJ\App_KernelDevDebugContainer([
    'container.build_hash' => '2x9EUrJ',
    'container.build_id' => '8d234ed5',
    'container.build_time' => 1645186344,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2x9EUrJ');
>>>>>>> 35d8e8d6c43cb91c2da1943efcc35b099aaf3e45
