<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAUEwEoj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAUEwEoj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAUEwEoj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAUEwEoj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAUEwEoj\App_KernelDevDebugContainer([
    'container.build_hash' => 'AUEwEoj',
    'container.build_id' => '1850f8c8',
    'container.build_time' => 1672163218,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAUEwEoj');
