<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIgOTDds\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIgOTDds/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIgOTDds.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIgOTDds\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIgOTDds\App_KernelDevDebugContainer([
    'container.build_hash' => 'IgOTDds',
    'container.build_id' => '630d1acf',
    'container.build_time' => 1645387424,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIgOTDds');
