<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqqcBPs\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqqcBPs/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXqqcBPs.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXqqcBPs\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXqqcBPs\App_KernelProdContainer([
    'container.build_hash' => 'XqqcBPs',
    'container.build_id' => 'ba03c386',
    'container.build_time' => 1645183491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqqcBPs');
