<?php

namespace ContainerJIzCNpd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiEmpleoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiEmpleoController' shared autowired service.
     *
     * @return \App\Controller\ApiEmpleoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiEmpleoController.php';

        $container->services['App\\Controller\\ApiEmpleoController'] = $instance = new \App\Controller\ApiEmpleoController(($container->privates['App\\Repository\\EmpleoRepository'] ?? $container->load('getEmpleoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\ApiEmpleoController', $container));

        return $instance;
    }
}
