<?php

namespace ContainerJIzCNpd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpleoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MNG5ObC.App\Entity\Empleo' shared service.
     *
     * @return \App\Entity\Empleo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MNG5ObC": it references class "App\\Entity\\Empleo" but no such service exists.');
    }
}
