<?php

namespace ContainerZp3Nl8T;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContenido2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DQnconH.App\Entity\Contenido' shared service.
     *
     * @return \App\Entity\Contenido
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DQnconH": it references class "App\\Entity\\Contenido" but no such service exists.');
    }
}
