<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9UcleKR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9UcleKR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9UcleKR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9UcleKR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9UcleKR\App_KernelDevDebugContainer([
    'container.build_hash' => '9UcleKR',
    'container.build_id' => 'caea41a7',
    'container.build_time' => 1644220096,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9UcleKR');
