<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6EBQk1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6EBQk1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU6EBQk1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU6EBQk1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU6EBQk1\App_KernelDevDebugContainer([
    'container.build_hash' => 'U6EBQk1',
    'container.build_id' => 'c9d6f970',
    'container.build_time' => 1644282634,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6EBQk1');
