<?php

namespace ContainerPixAuEi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiEventoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiEventoController' shared autowired service.
     *
     * @return \App\Controller\ApiEventoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiEventoController.php';

        $container->services['App\\Controller\\ApiEventoController'] = $instance = new \App\Controller\ApiEventoController(($container->privates['App\\Repository\\EventoRepository'] ?? $container->load('getEventoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ApiEventoController', $container));

        return $instance;
    }
}
