<?php

namespace ContainerXqqcBPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUsuarioControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ApiUsuarioController' shared autowired service.
     *
     * @return \App\Controller\ApiUsuarioController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ApiUsuarioController'] = $instance = new \App\Controller\ApiUsuarioController(($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\ApiUsuarioController', $container));

        return $instance;
    }
}
