<?php

namespace ContainerXqqcBPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContenidoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContenidoRepository' shared autowired service.
     *
     * @return \App\Repository\ContenidoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContenidoRepository'] = new \App\Repository\ContenidoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
