<?php

namespace ContainerXqqcBPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventoTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EventoType' shared autowired service.
     *
     * @return \App\Form\EventoType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EventoType'] = new \App\Form\EventoType();
    }
}
