<?php

namespace ContainerXqqcBPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpleo2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.qn8H32k.App\Entity\Empleo' shared service.
     *
     * @return \App\Entity\Empleo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qn8H32k": it references class "App\\Entity\\Empleo" but no such service exists.');
    }
}
