<?php

namespace ContainerXqqcBPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EventoRepository' shared autowired service.
     *
     * @return \App\Repository\EventoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EventoRepository'] = new \App\Repository\EventoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
